=== 1719781450/moqui/moqui/framework/xsd/entity-facade-conf-1.0.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!--
Copyright 2010 David E. Jones

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

 http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
-->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
    <xs:include schemaLocation="common-types-1.0.xsd"/>
    
    <!-- Root Element -->
    <xs:element name="entity-facade-conf">
        <xs:complexType>
            <xs:sequence>
                <xs:element maxOccurs="unbounded" ref="general-settings"/>
                <xs:element minOccurs="0" ref="app-server-jndi"/>
                <xs:element ref="transaction-factory"/>
                <xs:element maxOccurs="unbounded" ref="datasource"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="general-settings">
        <xs:complexType>
            <xs:attribute name="entity-eca-enabled" default="true" type="boolean"/>
            <xs:attribute name="distributed-cache-clear-enabled" default="false" type="boolean"/>
            <xs:attribute name="sequenced-id-prefix" type="xs:string"/>
            <xs:attribute name="default-group-name" type="xs:string" use="required"/>
        </xs:complexType>
    </xs:element>
    <xs:element name="app-server-jndi">
        <xs:complexType>
            <xs:attribute name="context-provider-url" type="xs:string"/>
            <xs:attribute name="initial-context-factory" type="xs:string"/>
            <xs:attribute name="url-pkg-prefixes" type="xs:string"/>
            <xs:attribute name="security-principal" type="xs:string"><xs:annotation><xs:documentation>The username</xs:documentation></xs:annotation></xs:attribute>
            <xs:attribute name="security-credentials" type="xs:string"><xs:annotation><xs:documentation>The password</xs:documentation></xs:annotation></xs:attribute>
        </xs:complexType>
    </xs:element>
    <xs:element name="transaction-factory">
        <xs:complexType>
            <xs:attribute name="factory-type" use="required">
                <xs:simpleType>
                    <xs:restriction base="xs:token">
                        <xs:enumeration value="internal"/>
                        <xs:enumeration value="jndi"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:attribute>
            <xs:attribute name="user-transaction-jndi-name" type="xs:string"/>
            <xs:attribute name="transaction-manager-jndi-name" type="xs:string"/>
        </xs:complexType>
    </xs:element>

    <xs:element name="datasource">
        <xs:complexType>
            <xs:sequence>
                <xs:choice minOccurs="1" maxOccurs="1">
                    <xs:element minOccurs="0" maxOccurs="1" ref="jndi-jdbc"/>
                    <xs:element minOccurs="0" maxOccurs="1" ref="inline-jdbc"/>
                </xs:choice>
            </xs:sequence>
            <xs:attribute name="group-name" type="xs:string" use="required"/>
            <xs:attribute name="database-config-name" type="xs:string" use="required"/>
            <xs:attribute name="schema-name" type="xs:string"/>
            <xs:attribute name="check-on-start" default="true" type="boolean"/>
            <xs:attribute name="add-missing-on-start" default="true" type="boolean"/>
            <xs:attribute name="check-pks-on-start" default="true" type="boolean"/>
            <xs:attribute name="check-fks-on-start" default="true" type="boolean"/>
            <xs:attribute name="check-fk-indices-on-start" default="true" type="boolean"/>
            <xs:attribute name="check-indices-on-start" default="true" type="boolean"/>
        </xs:complexType>
    </xs:element>
    <xs:element name="inline-jdbc">
        <xs:complexType>
            <xs:attribute name="jdbc-driver" type="xs:string" use="optional"/>
            <xs:attribute name="jdbc-uri" type="xs:string" use="required"/>
            <xs:attribute name="jdbc-username" type="xs:string" use="required"/>
            <xs:attribute name="jdbc-password" type="xs:string" use="required"/>
            <xs:attribute name="isolation-level" type="isolation-level"/>
            <xs:attribute name="pool-maxsize" type="xs:nonNegativeInteger" default="50"/>
            <xs:attribute name="pool-minsize" type="xs:nonNegativeInteger" default="2"/>
            <xs:attribute name="time-between-eviction-runs-millis" type="xs:nonNegativeInteger" default="600000"/>
            <xs:attribute name="pool-sleeptime" type="xs:nonNegativeInteger" default="300000"/>
            <xs:attribute name="pool-lifetime" type="xs:nonNegativeInteger" default="600000"/>
            <xs:attribute name="pool-deadlock-maxwait" type="xs:nonNegativeInteger" default="300000"/>
            <xs:attribute name="pool-deadlock-retrywait" type="xs:nonNegativeInteger" default="10000"/>
            <xs:attribute name="pool-jdbc-test-stmt" type="xs:string"/>
        </xs:complexType>
    </xs:element>
    <xs:element name="jndi-jdbc">
        <xs:complexType>
            <xs:attribute name="jndi-name" type="xs:string" use="required"/>
            <xs:attribute name="isolation-level" type="isolation-level"/>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== 1719781450/moqui/moqui/framework/conf-default/EntityFacadeConf.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!-- No copyright or license for configuration file, details here are not considered a creative work. -->

<entity-facade-conf xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:noNamespaceSchemaLocation="http://moqui.org/xsd/entity-facade-conf-1.0.xsd">

    <general-settings default-group-name="transactional" distributed-cache-clear-enabled="false"
                      entity-eca-enabled="true" sequenced-id-prefix=""/>

    <!-- this is used for both transaction and data source access -->
    <app-server-jndi context-provider-url="rmi://127.0.0.1:1099"
                     initial-context-factory="com.sun.jndi.rmi.registry.RegistryContextFactory"
                     url-pkg-prefixes="java.naming.rmi.security.manager"
                     security-principal="" security-credentials=""/>


    <!-- Use this one for the internal transaction manager -->
    <transaction-factory factory-type="internal"/>
    <!-- Use this one for getting the JTA objects from JNDI
    <transaction-factory factory-type="jndi" transaction-manager-jndi-name="java:comp/UserTransaction" user-transaction-jndi-name="java:comp/UserTransaction"/>
    -->
    <!-- UserTransaction JNDI name for most servers: java:comp/UserTransaction (most servers: Resin, Orion, OC4J, etc)
        JBoss (separate objects): "java:comp/UserTransaction" and "java:comp/TransactionManager"
    -->

    <datasource group-name="transactional" database-config-name="derby" schema-name="MOQUI">
        <inline-jdbc jdbc-uri="jdbc:derby:moqui_transactional;create=true"
                jdbc-username="moqui" jdbc-password="moqui"
                pool-minsize="2" pool-maxsize="50"/>
    </datasource>
    <datasource group-name="analytical" database-config-name="derby" schema-name="MOQUI">
        <inline-jdbc jdbc-uri="jdbc:derby:moqui_analytical;create=true"
                jdbc-username="moqui" jdbc-password="moqui"
                pool-minsize="2" pool-maxsize="10"/>
    </datasource>
    <datasource group-name="tenantcommon" database-config-name="derby" schema-name="MOQUI">
        <inline-jdbc jdbc-uri="jdbc:derby:moqui_tenantcommon;create=true"
                jdbc-username="moqui" jdbc-password="moqui"
                pool-minsize="2" pool-maxsize="10"/>
    </datasource>

    <!-- some examples of how other databases would be configured -->
    <!-- PostgreSQL
    <datasource group-name="transactional" database-config-name="postgres" schema-name="public">
        <inline-jdbc jdbc-uri="jdbc:postgresql://127.0.0.1/moqui_transactional"
                jdbc-username="moqui" jdbc-password="moqui"
                pool-minsize="2" pool-maxsize="50"/>
    </datasource>
    -->
    <!-- MySQL
    <datasource group-name="transactional" database-config-name="mysql"
                check-pks-on-start="false">
        <inline-jdbc jdbc-uri="jdbc:mysql://127.0.0.1/moqui_transactional?autoReconnect=true"
                jdbc-username="moqui" jdbc-password="moqui"
                pool-minsize="2" pool-maxsize="50"/>
    </datasource>
    -->
    <!-- Oracle
    <datasource group-name="transactional" database-config-name="oracle" schema-name="MOQUI">
        <inline-jdbc jdbc-uri="jdbc:oracle:thin:@127.0.0.1:1521:moqui_transactional"
                jdbc-username="moqui" jdbc-password="moqui"
                pool-minsize="2" pool-maxsize="50"/>
    </datasource>
    -->
</entity-facade-conf>
